env:
  browser: true
  es6: true
  node: true
  mocha: true
plugins:
  - jest
  - supertest-as-promised
extends: 'airbnb-base'
parserOptions:
  ecmaVersion: 2016
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
